
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ramesh216/github-docekerimage:2.0.0 .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ramesh216/github-docekerimage:2.0.0

      - name: Logout from Docker
        run: docker logout